import { AIMessage } from '@langchain/core/messages'
import { GraphState } from '../state.js'
import { getInstallationOctokit } from '../../github/appClient.js'
import { runInSandbox } from '../../sandbox/runInSandbox.js'
import sandboxManager from '../../sandbox/SandboxManager.js'
import pool from '../../db/client.js'

function toTitleCase(str: string): string {
  return str
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ')
}

function extractWhatAreWeBuildingSection(techSpecContent: string): string {
  const match = techSpecContent.match(
    /##\s+What are we building\?[\s\S]*?(?=\n##\s|\n---\s*\n##\s|$)/i,
  )
  if (!match) return ''
  const lines = match[0].split('\n')
  return lines.slice(1).join('\n').trim()
}

export async function openPrNode(
  state: typeof GraphState.State,
): Promise<Partial<typeof GraphState.State>> {
  console.log('[openPr] called')

  const {
    threadId,
    repoOwner,
    repoName,
    gitBranch,
    featureRequest,
    techSpecContent,
    sandboxPath,
    userLogin,
  } = state

  // 1. Get installation Octokit
  const octokit = await getInstallationOctokit(repoOwner, repoName)

  // 2. Push the feature branch to GitHub
  await runInSandbox(sandboxPath, `git push origin ${gitBranch}`)

  // 3. Build PR title and body
  const prTitle = toTitleCase(featureRequest).slice(0, 70)
  const whatSection = extractWhatAreWeBuildingSection(techSpecContent)
  const prBody = [
    whatSection,
    '',
    '---',
    `> Initiated by @${userLogin}. Generated by the [Coding Orchestrator](https://github.com/${repoOwner}/${repoName}).`,
  ]
    .join('\n')
    .trim()

  // 4. Open the PR
  const { data: pr } = await octokit.pulls.create({
    owner: repoOwner,
    repo: repoName,
    title: prTitle,
    body: prBody,
    head: gitBranch,
    base: 'develop',
  })

  const prUrl = pr.html_url

  // 5. Update orchestrator_sessions
  await pool.query(
    `UPDATE orchestrator_sessions SET status = 'finished', pr_url = $1, updated_at = NOW() WHERE thread_id = $2`,
    [prUrl, threadId],
  )

  // 6. Tear down the sandbox
  await sandboxManager.destroy(threadId)

  return {
    prUrl,
    messages: [new AIMessage(`PR opened: ${prUrl}`)],
  }
}
